<!-- Страница Условий сервиса -->
<!doctype html>
<html lang="{LANGUAGE}">

<head>
    <?php
        # подключаем общие разделы <HEAD>
        require COMMON_HEAD_S;
    ?>
<body>
    <?php
        # секция Навигации
        require TPL_NAV_SIMPLE_SECTION;
        # секция ввода нового пароля
        require TPL_UNDER_MAINTENANCE_SECTION;

        //require TPL_FOOTER_SECTION;
    ?>
</body>
</html>