<!--Секция сброса пароля-->
<?php # активируем компонент проверки восстановления пароля
    $reset = new \components\resetPasswCheckComponent();
    // проверяем валидность входной ссылки и в зависимости от формируем страницу
    if ($reset->getCheck()) {
?>
<!-- блок если подтверждаем сброс пароля -->
<div class="container">
    <div class="row m-4">
        <div class="col text-center">
            <h5>Введите новый пароль</h5>
        </div>
    </div>
    <form id="reset_password_form" action="#">
        <div class="form-row justify-content-md-center my-2 mr-2">
            <div class="col-md-5">
                <div class="form-group">
                    <label for="user_email">E-mail*</label>
                    <input type="email" class="form-control" id="user_email" name="user_email" maxlength="40" 
                        value="<?=$reset->getLogin()?>" readonly required>
                </div>
            </div>
        </div>

        <div class="form-row justify-content-center my-2 mr-2">
            <div class="col-md-5 offset-md-2">
                <div class="form-group">
                    <label for="user_password">Пароль*</label>
                    <input type="password" class="form-control" id="user_password" name="user_password" minlength="6"
                        maxlength="20" required>
                    <small class="form-text text-muted">Пароль должен содержать от 6 до 20 латинских символов, включая числа и минимум одну
                        заглавную букву
                    </small>
                </div>
            </div>
            <div class="col-md-2 d-flex align-items-center">
                <h5>
                    <span class="mb-3 badge" id="password1_ok"></span>
                </h5>
            </div>
        </div>

        <div class="form-row justify-content-center mr-2">
            <div class="col-md-5 offset-md-2">
                <div class="form-group">
                    <label for="user_password2">Повторите пароль*</label>
                    <input type="password" class="form-control" id="user_password2" minlength="6" maxlength="20"
                        required>
                </div>
            </div>
            <div class="col-md-2 d-flex align-items-end">
                <h5>
                    <span class="mb-3 badge" id="password2_ok"></span>
                </h5>
            </div>
        </div>
        <div class="form-row mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <span id="notification"></span>
            </div>
        </div>
        <div class="form-row ">
            <div class="col text-center">
                <input id="save_passw" form="reset_password_form" type="submit" class="btn sx-btn-on" value="Сохранить">
            </div>
        </div>

    </form>
</div>

<?php
    } else {
?>
<!-- блок если не подтверждаем сброс пароля -->
<div class="container">
    <div class="row mt-5">
        <div class="col text-center">
            <h5><?=$reset->getErrorMessage()?></h5>
        </div>
    </div>
</div>
<?php
    }
?>