<!doctype html>
<html lang="{LANGUAGE}">

<head>
    <?php
        # подключаем секцию <HEAD>
        require COMMON_HEAD_S;
    ?>
    <!-- page CSS -->
    
    <!-- Page JS -->
    <script defer src="/templates/pages/test_page/js/page.js" type="module"></script>
    
</head>

<body>
    <?php
        # секция Общая навигация страницы
        require TPL_TEST_PAGE_S;
        
    ?>
</body>

</html>